export const unit8B1Vocab = [
  { front: 'elderly', back: '上了年纪的', pos: 'adj.' },
  { front: 'elder', back: '年长的；长辈', pos: 'adj./n.' },
  { front: 'eldest', back: '最年长的', pos: 'adj.' },
  { front: 'offer', back: '主动提出；提议；报价', pos: 'v./n.' },
  { front: 'offered', back: '主动提出 (过去式/过去分词)', pos: 'v.' },
  { front: 'serious', back: '严重的；严肃的', pos: 'adj.' },
  { front: 'seriously', back: '严重地；严肃地', pos: 'adv.' },
  { front: 'seriousness', back: '严重性；严肃', pos: 'n.' },
  { front: 'disease', back: '病；疾病', pos: 'n.' },
  { front: 'cancer', back: '癌；癌症', pos: 'n.' },
  { front: 'cancerous', back: '癌的；患癌的', pos: 'adj.' },
  { front: 'spirits', back: '情绪；心境；烈酒', pos: 'n.' },
  { front: 'spirit', back: '精神；心灵；勇气', pos: 'n.' },
  { front: 'pain', back: '痛苦；苦恼；使痛苦', pos: 'n./v.' },
  { front: 'painful', back: '痛苦的；令人疼痛的', pos: 'adj.' },
  { front: 'painless', back: '无痛的', pos: 'adj.' },
  { front: 'belong', back: '适应；合得来；属于', pos: 'v.' },
  { front: 'belongings', back: '所有物；行李', pos: 'n.' },
  { front: 'belonging', back: '归属感', pos: 'n.' },
  { front: 'spare', back: '空闲的；空余的；抽出；匀出', pos: 'adj./v.' },
  { front: 'sparing', back: '节俭的；吝啬的', pos: 'adj.' },
  { front: 'volunteer', back: '自愿做；志愿者', pos: 'v./n.' },
  { front: 'voluntary', back: '自愿的；志愿的', pos: 'adj.' },
  { front: 'joy', back: '高兴；愉快；喜悦', pos: 'n.' },
  { front: 'joyful', back: '快乐的；令人高兴的', pos: 'adj.' },
  { front: 'joyfully', back: '快乐地；高兴地', pos: 'adv.' },
  { front: 'lose', back: '丧失；失去', pos: 'v.' },
  { front: 'lost', back: '丧失；失去 (过去式/过去分词)', pos: 'v.' },
  { front: 'losing', back: '丧失；失去 (现在分词)', pos: 'v.' },
  { front: 'loss', back: '损失；丧失', pos: 'n.' },
  { front: 'loser', back: '失败者', pos: 'n.' },
  { front: 'raise', back: '筹募；举起；提高', pos: 'v.' },
  { front: 'raised', back: '筹募；举起；提高 (过去式/过去分词)', pos: 'v.' },
  { front: 'raising', back: '提高；筹款', pos: 'n.' },
  { front: 'pound', back: '英镑；猛击；砰砰作响', pos: 'n./v.' },
  { front: 'structure', back: '结构；组织；安排', pos: 'n./v.' },
  { front: 'structured', back: '有组织的；有条理的', pos: 'adj.' },
  { front: 'permission', back: '准许；许可', pos: 'n.' },
  { front: 'permit', back: '允许；许可', pos: 'v.' },
  { front: 'permissible', back: '可允许的', pos: 'adj.' },
  { front: 'arrange', back: '排列；布置；安排', pos: 'v.' },
  { front: 'arranged', back: '排列；布置；安排 (过去式/过去分词)', pos: 'v.' },
  { front: 'arrangement', back: '安排；布置', pos: 'n.' },
  { front: 'donate', back: '捐赠；赠送', pos: 'v.' },
  { front: 'donation', back: '捐赠物；捐赠', pos: 'n.' },
  { front: 'donator', back: '捐赠物或金钱的人', pos: 'n.' },
  { front: 'donor', back: '捐赠物如献血、捐献器官的人', pos: 'n.' },
  { front: 'mighty', back: '巨大的；非凡的；强有力的', pos: 'adj.' },
  { front: 'mightily', back: '强烈地；有力地', pos: 'adv.' },
  { front: 'mightiness', back: '强大；威力', pos: 'n.' },
  { front: 'pleasant', back: '令人愉快的；宜人的', pos: 'adj.' },
  { front: 'please', back: '使高兴；取悦', pos: 'v.' },
  { front: 'pleasure', back: '愉快；乐事', pos: 'n.' },
  { front: 'pleased', back: '高兴的；满意的', pos: 'adj.' },
  { front: 'ease', back: '减轻；缓解；轻松；舒适', pos: 'v./n.' },
  { front: 'easy', back: '容易的；轻松的', pos: 'adj.' },
  { front: 'easily', back: '容易地', pos: 'adv.' },
  { front: 'ache', back: '疼痛；隐痛', pos: 'v./n.' },
  { front: 'aching', back: '疼痛的；酸痛的', pos: 'adj.' }
];

export const unit8B1Phrases = [
  { front: 'elderly people', back: '老年人' },
  { front: 'care for the elderly', back: '照顾老人' },
  { front: 'offer to do sth.', back: '主动提出做某事' },
  { front: 'offer sb sth', back: '主动提供某人某物' },
  { front: 'offer sth to sb.', back: '主动提供某物给某人' },
  { front: 'job offer', back: '工作邀请' },
  { front: 'serious problem', back: '严重问题' },
  { front: 'serious illness', back: '重病' },
  { front: 'take sth. seriously', back: '认真对待某事' },
  { front: 'be serious about doing sth', back: '对某事是认真严肃的' },
  { front: 'heart disease', back: '心脏病' },
  { front: 'infectious diseases', back: '传染病' },
  { front: 'fight against cancer', back: '对抗癌症' },
  { front: 'in high spirits', back: '情绪高涨' },
  { front: 'in low spirits', back: '情绪低落' },
  { front: 'in a lot of pain', back: '处于痛苦中' },
  { front: 'physical pain', back: '身体疼痛' },
  { front: 'belong to sb.', back: '属于' },
  { front: 'belong in', back: '适合于' },
  { front: 'a sense of belonging', back: '归属感' },
  { front: 'spare time', back: '空闲时间' },
  { front: 'spare a few minutes', back: '抽出几分钟' },
  { front: 'volunteer to do sth.', back: '自愿做某事' },
  { front: 'voluntary work', back: '志愿工作' },
  { front: 'full of joy', back: '充满喜悦' },
  { front: 'to one\'s joy', back: '令某人高兴的是' },
  { front: 'lose one\'s way', back: '迷路' },
  { front: 'lose weight', back: '减肥' },
  { front: 'lose heart', back: '灰心' },
  { front: 'raise money', back: '筹钱' },
  { front: 'raise one\'s hand', back: '举手' },
  { front: 'raise awareness', back: '提高意识' },
  { front: 'sentence structure', back: '句子结构' },
  { front: 'structure a plan', back: '规划方案' },
  { front: 'ask for permission', back: '请求许可' },
  { front: 'give sb permission to do sth', back: '给某人做某事的许可' },
  { front: 'with one\'s permission', back: '经某人许可' },
  { front: 'without one\'s permission', back: '未经许可' },
  { front: 'permit doing sth.', back: '允许做某事' },
  { front: 'permit sb. to do sth.', back: '允许某人做某事' },
  { front: 'arrange a meeting', back: '安排会议' },
  { front: 'arrange flowers', back: '插花' },
  { front: 'flower arranging', back: '插花' },
  { front: 'make arrangements', back: '做安排' },
  { front: 'donate sth to sb/sth', back: '捐赠某物给某人/某物' },
  { front: 'mighty ocean', back: '浩瀚的海洋' },
  { front: 'mighty river', back: '浩瀚的河流' },
  { front: 'mighty wind', back: '强风' },
  { front: 'mighty effort', back: '巨大的努力' },
  { front: 'pleasant weather', back: '宜人的天气' },
  { front: 'pleasant surprise', back: '惊喜' },
  { front: 'ease pain', back: '缓解疼痛' },
  { front: 'with ease', back: '轻松地' },
  { front: 'at ease', back: '自在；放松' },
  { front: 'have a headache', back: '头痛' },
  { front: 'ache all over', back: '浑身疼痛' },
  { front: 'stomachache', back: '胃痛' },
  { front: 'the aching', back: '疼痛' },
  { front: 'do voluntary work', back: '做志愿工作' },
  { front: 'take part in voluntary work', back: '参与志愿工作' },
  { front: 'disabled people', back: '残障人士' },
  { front: 'people with disabilities', back: '残障人士' },
  { front: 'able-bodied people', back: '健全人士' },
  { front: 'provide facilities for disabled people', back: '为残障人士提供设施' },
  { front: 'look after', back: '照料；照顾' },
  { front: 'take care of', back: '照顾' },
  { front: 'care for', back: '照料' },
  { front: 'look after the elderly', back: '照顾老人' },
  { front: 'suffer from', back: '遭受；患……病' },
  { front: 'be free from', back: '免受……困扰' },
  { front: 'suffer from poverty', back: '遭受贫困' },
  { front: 'cheer somebody up', back: '(使)高兴起来' },
  { front: 'lift one\'s mood', back: '改善心情' },
  { front: 'brighten one\'s day', back: '让一天变得愉快' },
  { front: 'bring somebody down', back: '使某人沮丧' },
  { front: 'upset somebody', back: '使某人难过' },
  { front: 'raise one\'s spirits', back: '使某人振奋' },
  { front: 'boost one\'s morale', back: '鼓舞士气' },
  { front: 'lift one\'s spirits', back: '使某人振作' },
  { front: 'in order to', back: '目的是；为了' },
  { front: 'so as to', back: '为了' },
  { front: 'with the aim of', back: '旨在' },
  { front: 'by accident', back: '偶然' },
  { front: 'accidentally', back: '意外地' },
  { front: 'in order to do sth.', back: '为了做某事' },
  { front: 'in need', back: '在危难中；在困境中的' },
  { front: 'in trouble', back: '处于困境' },
  { front: 'in difficulty', back: '遇到困难' },
  { front: 'in comfort', back: '生活舒适' },
  { front: 'in prosperity', back: '生活富足' },
  { front: 'learn flower arranging', back: '学习插花' },
  { front: 'take a flower arranging class', back: '插花课' },
  { front: 'tidy up', back: '收拾；整理' },
  { front: 'clean up', back: '打扫干净' },
  { front: 'mess up', back: '弄乱' },
  { front: 'make a mess', back: '制造混乱' },
  { front: 'tidy up the room', back: '整理房间' },
  { front: 'in vain', back: '枉费心机；徒劳无益' },
  { front: 'try in vain', back: '徒劳尝试' },
  { front: 'do sth. in vain', back: '白费力气做某事' }
];

export const unit8B1Sentences = [
  { front: 'We should be polite and helpful to elderly people.', back: '我们应该对老年人有礼貌并乐于助人。' },
  { front: 'The community center offers free meals to the elderly.', back: '社区中心为老年人提供免费餐食。' },
  { front: 'He offered to help me carry the heavy boxes.', back: '他主动提出帮我搬重箱子。' },
  { front: 'The flood caused serious damage to the village.', back: '洪水给村庄造成了严重的破坏。' },
  { front: 'You need to take your studies more seriously.', back: '你需要更认真地对待你的学习。' },
  { front: 'The spread of the disease was controlled quickly.', back: '这种疾病的传播很快得到了控制。' },
  { front: 'He is receiving treatment for lung cancer.', back: '他正在接受肺癌治疗。' },
  { front: 'Early detection can improve cancer survival rates.', back: '早期检测可以提高癌症存活率。' },
  { front: 'She was in high spirits after winning the competition.', back: '赢得比赛后，她情绪高涨。' },
  { front: 'He has been in low spirits since he lost his job.', back: '自从失业后，他一直情绪低落。' },
  { front: 'She cried out in pain when she fell off her bike.', back: '她从自行车上摔下来时疼得叫出声。' },
  { front: 'The operation was painful but necessary.', back: '手术很痛苦，但很有必要。' },
  { front: 'This book belongs to my sister.', back: '这本书是我妹妹的。' },
  { front: 'She feels like she belongs in this new city.', back: '她觉得她属于这座新城市。' },
  { front: 'Do you have any spare time to help me with this?', back: '你有空帮我做这个吗？' },
  { front: 'Can you spare me a pen? I forgot mine at home.', back: '你能借我一支笔吗？我把我的忘在家里了。' },
  { front: 'She volunteers to look after the animals at the animal shelter every weekend.', back: '她每个周末都自愿去动物收容所照顾动物。' },
  { front: 'To my joy, I passed the exam with good grades.', back: '令我高兴的是，我以优异的成绩通过了考试。' },
  { front: 'He lost his keys on the way to work.', back: '他在上班路上弄丢了钥匙。' },
  { front: 'Don\'t lose heart—you\'ll do better next time.', back: '别灰心，你下次会做得更好。' },
  { front: 'They organized a charity event to raise money for the poor.', back: '他们组织了一场慈善活动为穷人筹款。' },
  { front: 'They organized a money-raising activity to buy clothes for elderly people.', back: '他们组织了一次筹款活动为老年人买衣服。' },
  { front: 'The book costs 15 pounds.', back: '这本书售价15英镑。' },
  { front: 'The structure of the old building was damaged in the earthquake.', back: '这座老建筑的结构在地震中受损。' },
  { front: 'We need to structure our work more efficiently.', back: '我们需要更高效地安排工作。' },
  { front: 'You must ask for permission before leaving the classroom.', back: '离开教室前你必须请求许可。' },
  { front: 'He entered the room without permission.', back: '他未经许可就进了房间。' },
  { front: 'We need to arrange a time to discuss the project.', back: '我们需要安排时间讨论这个项目。' },
  { front: 'Some businesses have agreed to donate computers to schools.', back: '一些企业已同意向学校捐赠电脑。' },
  { front: 'The mighty ocean stretched out before us.', back: '浩瀚的海洋在我们面前铺展开。' },
  { front: 'With a mighty effort, he lifted the heavy box.', back: '他用尽全力举起了那个重箱。' },
  { front: 'The hotel has a pleasant view of the mountains.', back: '这家酒店能看到宜人的山景。' },
  { front: 'The medicine will help ease your headache.', back: '这药能帮你缓解头痛。' },
  { front: 'She finished the task with ease.', back: '她轻松完成了任务。' },
  { front: 'My back aches after sitting at the desk all day.', back: '在书桌前坐了一整天后，我的背很痛。' },
  { front: 'She woke up with a terrible ache in her shoulder.', back: '她醒来时肩膀剧痛。' },
  { front: 'We prepared a pleasant party to cheer our friend up.', back: '我们准备了一个愉快的派对来让我们的朋友高兴起来。' },
  { front: 'She got up early in order to catch the first bus.', back: '她早起为了赶上早班车。' },
  { front: 'The charity provides food and clothes for families in need.', back: '这个慈善机构为穷困家庭提供食物和衣物。' },
  { front: 'Flower arranging is a popular hobby among middle-aged women.', back: '插花在中年妇女中是一项受欢迎的爱好。' },
  { front: 'I shall not live in vain.', back: '我将不会虚度此生。' },
  { front: 'Many teenagers want to do voluntary work to help the people around them.', back: '很多青少年想要做志愿工作来帮助身边的人。' },
  { front: 'We get up early every morning in order to catch the school bus on time.', back: '我们每天早上早起，为了准时赶上校车。' },
  { front: 'The teacher\'s encouraging words raised our spirits before the English competition.', back: '老师鼓舞人心的话语，在英语竞赛前鼓舞了我们的士气。' },
  { front: 'The little girl suffers from a serious illness, but she never gives up.', back: '这个小女孩患有一种严重的疾病，但她从未放弃。' },
  { front: 'It\'s our duty to respect and help disabled people in public places.', back: '在公共场所尊重并帮助残障人士是我们的责任。' },
  { front: 'My mother asked me to look after my little brother when she was out.', back: '妈妈出门的时候，让我照顾我的小弟弟。' },
  { front: 'The kind woman often provides food and clothes for people in need.', back: '这位善良的女士经常为处于困境中的人提供食物和衣物。' },
  { front: 'They tried many times to fix the machine, but all their efforts were in vain.', back: '他们尝试了很多次去修理这台机器，但所有的努力都是徒劳的。' },
  { front: 'Let\'s tell some jokes to cheer him up —he looks sad today.', back: '我们来讲几个笑话使他振作起来吧 —— 他今天看起来很伤心。' },
  { front: 'Don\'t bother him because he has been in low spirits since he failed the test.', back: '别去打扰他，因为自从考试失利后，他就一直情绪低落。' }
];
